### ISSUE TITLE
WinError 2

### ISSUE THREAD

**Issue by Bankaimaster999** [i6od/Voice-to-Voice-Ooba#1]
Neep help; getting this error after running start.bat
- requirements seemed to be installed properly without issues.
- oobabooga is running fine without issues as well as Vtuber studio.

![1](https://github.com/i6od/Voice-to-Voice-Ooba/assets/63358235/938c2dc1-67ed-44e2-a4db-f4d180c86e0e)

**Comment by i6od** [comment]
Looks like your computer is having troubles with ffmpeg,

**Comment by i6od** [comment]
https://www.youtube.com/watch?v=EyIIvctDhYc

please follow this youtube tutorial to install ffmpeg and path it in your environment variabled.
